### ISSUE TITLE
Internal git

### ISSUE THREAD

**Issue by norico** [imath/entrepot#18]
Bonjour. 
Est il possible défaire la même chose avec un git d’entreprise ?

**Comment by imath** [comment]
Bonjour,

J'imagine, mais c'est l'histoire d'une autre extension, pas celle-ci 😉

**Comment by norico** [comment]
Désolé, jetais en vacances,
mon service informatique a un git entreprise en intranet, nous avons donc un gitlab.mon-entreprise.local. Je suppose que l'adresse de GitHub est dans les sources? 
je souhaiterai juste la modifier pour mettre l'adresse de notre gitlab.
d'après vous ce n'est pas possible ...
Merci.

**Comment by imath** [comment]
Tout est possible, bien entendu. Je vous conseille néanmoins d'envisager cette extension https://github.com/afragen/github-updater qui me parait plus adaptée.

**Comment by norico** [comment]
Merci je vais regarder
